version: '3.8'

services:

  scraper:
    build: ./src/scraper
    stdin_open: true
    tty: true
    shm_size: 1gb
    volumes:
      - C:\Users\Alex\Documents\Finances:/app/Finances/
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0

  db:
    build: ./src/database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data    

  backend:
    build: ./src/backend
    stdin_open: true
    tty: true
    volumes:
      - C:\Users\Alex\Documents\Finances:/app/Finances/
    ports:
      - 5050:5000
    command: flask run --host=0.0.0.0



volumes:
  postgres_data:
    driver: local  