version: '3.8'

services:

  scraper:
    build: ./src/scraper
    stdin_open: true
    tty: true
    shm_size: 1gb
    volumes:
      - C:\Users\Alex\Documents\Finances:/app/Finances/
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0

  db:
    build: ./src/database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data    


  # item_updater:
  #   build: ./
  #   stdin_open: true
  #   tty: true
  #   shm_size: 1gb
  #   volumes:
  #     - receipts:/app/Finances/receipts/
  #   command: python /app/src/scratch/scraper_class_scratch.py



volumes:
  postgres_data:
    driver: local
  # receipts:
  #   driver: local    