version: '3.8'

services:

  scraper:
    build: ./src/scraper
    stdin_open: true
    tty: true
    volumes:
      - receipts:/app/Finances/receipts/
    command: python /app/scraper/scraper.py
    profiles:
      - add_items

  item_updater:
    build: ./
    stdin_open: true
    tty: true
    shm_size: 1gb
    volumes:
      - receipts:/app/Finances/receipts/
    command: python /app/src/postgres_scratch.py
    depends_on:
      - db
      - scraper
    profiles:
      - add_items

  test:
    build: ./
    stdin_open: true
    tty: true
    shm_size: 1gb
    volumes:
      - receipts:/app/Finances/receipts/
    command: python /app/src/test_2_scratch.py
    profiles:
      - test

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  receipts:
    driver: local   
  postgres_data:
    driver: local